osx_image: xcode9
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - brew update
  - bundle install && brew bundle
  - bunble exec pod repo remove master
  - bundle exec pod setup
script:
  - bundle exec fastlane run_tests
after_success:
  - bundle exec fastlane ci_framework_deploy
